fix: fix token info table
UMAprotocol/umaverse pull request #89
Opened 2022-04-06 10:59 UTC by amateima

Signed-off-by: amateima <amatei@umaproject.org>

This PR improves the UI of the Token Information table by showing the address on a single line and by aligning the Copy address button to be centered vertically

<img width="727" alt="Screenshot 2022-04-06 at 13 54 45" src="https://user-images.githubusercontent.com/89395931/161960378-9dbba000-d7f2-4d02-adc8-93054cdc2958.png">

2022-04-06 12:55 UTC, daywiss commented
looks like we need to update the env vars to the right backend

2022-04-06 12:55 UTC, daywiss approved these changes

2022-04-06 15:03 UTC, Tulun approved these changes

2022-04-11 08:24 UTC, Gamaranto requested changes
PR looks good, but the build is broken, not sure if related to this PR or it just broke for other reasons

2022-04-11 08:37 UTC, amateima commented
> PR looks good, but the build is broken, not sure if related to this PR or it just broke for other reasons

It is not related to the PR. I'm looking into it

2022-04-15 14:41 UTC, Gamaranto approved these changes

2022-04-15 14:42 UTC, merged